"""Deterministic caption timing — no transcription API needed since we already have
the exact script text (it was never transcribed from audio, it was generated by the
Script agent). Splits the script into caption-sized chunks and distributes them
proportionally to word count across the known narration duration. Output feeds
Remotion's captionCues inputProp directly (Video Assembly renders captions natively,
no ffmpeg subtitle burn-in step).
"""
import re


def build_cues(script_text: str, duration_seconds: float, max_words_per_caption: int = 8) -> list:
    words = script_text.split()
    if not words:
        return []

    chunks = [words[i:i + max_words_per_caption] for i in range(0, len(words), max_words_per_caption)]
    seconds_per_word = duration_seconds / len(words)

    cues = []
    cursor = 0.0
    for chunk in chunks:
        chunk_duration = seconds_per_word * len(chunk)
        start, end = cursor, cursor + chunk_duration
        text = re.sub(r"\s+", " ", " ".join(chunk)).strip()
        cues.append({"start_seconds": round(start, 3), "end_seconds": round(end, 3), "text": text})
        cursor = end
    return cues
